version: "3.9"

networks:
  gestaovotos-network:
    driver: bridge

services:
  gestaovotos-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"
    networks:
      - gestaovotos-network

  gestaovotos-api-1:
    image: gestaovotos-api
    command: ["/wait-for-it.sh", "gestaovotos-mysql:3306", "-t", "30", "--", "java", "-jar", "gestaovotos-api.jar"]

    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

      - DB_HOST=${DB_HOST}
      - JDBC_DATABASE_USERNAME=${JDBC_DATABASE_USERNAME}
      - JDBC_DATABASE_PASSWORD=${JDBC_DATABASE_PASSWORD}

    networks:
      - gestaovotos-network
    depends_on:
      - gestaovotos-mysql
  gestaovotos-api-2:
    image: gestaovotos-api
    command: ["/wait-for-it.sh", "gestaovotos-mysql:3306", "-t", "30", "--", "java", "-jar", "gestaovotos-api.jar"]

    environment:
      - DB_HOST=${DB_HOST}

      - SPRING_SESSION_STORE_TYPE=${SPRING_SESSION_STORE_TYPE}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

      - JDBC_DATABASE_USERNAME=${JDBC_DATABASE_USERNAME}
      - JDBC_DATABASE_PASSWORD=${JDBC_DATABASE_PASSWORD}

    networks:
      - gestaovotos-network
    depends_on:
      - gestaovotos-mysql
  gestaovotos-nginx-proxy-reverso:
    image: nginx
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - gestaovotos-network
    depends_on:
      - gestaovotos-api-1
      - gestaovotos-api-2
